version: '3.8'

services:
  master-service:
    build: ./master
    container_name: master_container
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mapreduce_network
    ports:
      - "5001:5001"
    environment:
      - MAPPER_URLS=http://mapper-service-1:5002,http://mapper-service-2:5002,http://mapper-service-3:5002
      - REDUCER_URLS=http://reducer-service-1:5003,http://reducer-service-2:5003
    volumes:
      - ./master:/app
    command: python -m src.master

  mapper-service-1:
    build: ./mapper
    container_name: mapper_container_1
    environment:
      - MAPPER_ID=1
      - MASTER_URL=http://master-service:5001
      - MAPPER_URL=http://mapper-service-1:5002  # Fixed URL
    networks:
      - mapreduce_network
    ports:
      - "5002:5002"
    volumes:
      - ./mapper:/app
    command: python -m src.mapper

  mapper-service-2:
    build: ./mapper
    container_name: mapper_container_2
    environment:
      - MAPPER_ID=2
      - MASTER_URL=http://master-service:5001
      - MAPPER_URL=http://mapper-service-2:5002  # Fixed URL
    networks:
      - mapreduce_network
    ports:
      - "5012:5002"
    volumes:
      - ./mapper:/app
    command: python -m src.mapper

  mapper-service-3:
    build: ./mapper
    container_name: mapper_container_3
    environment:
      - MAPPER_ID=3
      - MASTER_URL=http://master-service:5001
      - MAPPER_URL=http://mapper-service-3:5002  # Fixed URL
    networks:
      - mapreduce_network
    ports:
      - "5022:5002"
    volumes:
      - ./mapper:/app
    command: python -m src.mapper

  reducer-service-1:
    build: ./reducer
    container_name: reducer_container_1
    environment:
      - REDUCER_ID=1
      - MASTER_URL=http://master-service:5001
      - REDUCER_URL=http://reducer-service-1:5003  # Fixed URL
    networks:
      - mapreduce_network
    ports:
      - "5003:5003"
    volumes:
      - ./reducer:/app
    command: python -m src.reducer

  reducer-service-2:
    build: ./reducer
    container_name: reducer_container_2
    environment:
      - REDUCER_ID=2
      - MASTER_URL=http://master-service:5001
      - REDUCER_URL=http://reducer-service-2:5003  # Fixed URL
    networks:
      - mapreduce_network
    ports:
      - "5013:5003"
    volumes:
      - ./reducer:/app
    command: python -m src.reducer

networks:
  mapreduce_network:
    driver: bridge