version: '3.8'

services:
  master-service:
    build: ./master
    container_name: master_container
    depends_on:
      - mapper-service
    networks:
      - mapreduce_network
    ports:
      - "5001:5001"  # Expose Master on host port 5001
    environment:
      - MAPPER_URLS=http://mapper-service:5002 
    volumes:
      - ./master:/app
    command: python -m src.master  # Changed to use src module

  mapper-service:
    build: ./mapper
    container_name: mapper_container
    environment:
      - MAPPER_ID=1
      - MASTER_URL=http://master-service:5001
    networks:
      - mapreduce_network
    ports:
      - "5002:5002"  # Expose Mapper on host port 5002
    volumes:
      - ./mapper:/app
    command: python -m src.mapper  # Changed to use src module

  reducer-service:
    build: ./reducer
    container_name: reducer_container
    environment:
      - REDUCER_ID=1
      - MASTER_URL=http://master-service:5001
      - REDUCER_URL=http://reducer-service:5003
    networks:
      - mapreduce_network
    ports:
      - "5003:5003"  # Expose Reducer on host port 5003
    volumes:
      - ./reducer:/app
    command: python -m src.reducer  # Changed to use src module

networks:
  mapreduce_network:
    driver: bridge