apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapper
  labels:
    app: mapper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mapper
  template:
    metadata:
      labels:
        app: mapper
    spec:
      containers:
      - name: mapper
        image: kyronnyoro/mapreduce-mapper:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: mapper-service
spec:
  selector:
    app: mapper
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP
