apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: kyronnyoro/mapreduce-master:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  selector:
    app: master
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
