apiVersion: apps/v1
kind: Deployment
metadata:
  name: reducer
  labels:
    app: reducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reducer
  template:
    metadata:
      labels:
        app: reducer
    spec:
      containers:
      - name: reducer
        image: kyronnyoro/mapreduce-reducer:latest
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: reducer-service
spec:
  selector:
    app: reducer
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP
